name = "TrackingTimers"
uuid = "88ba133c-8695-4d62-9a5c-bcf16b6d2e1a"
authors = ["Eric P. Hanson"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
