name: Documentation
on:
  push:
    branches: "main"
    tags: ["*"]
  pull_request:
  release:
jobs:
  docs:
    name: Documentation
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using TrackingTimers
            DocMeta.setdocmeta!(TrackingTimers, :DocTestSetup, :(using TrackingTimers); recursive=true)
            doctest(TrackingTimers)'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
